// Generated by tools/prepare_assets.py: sprite sheet sizes and per-frame durations (ms).
window.ABOUT_ME_SPRITES = {
 "sailor-bee": {
  "src": "assets/sprites/sailor-bee.png",
  "w": 136,
  "h": 208,
  "frames": 10,
  "durations": [
   320,
   320,
   170,
   170,
   170,
   170,
   320,
   320,
   130,
   320
  ]
 },
 "moon": {
  "src": "assets/sprites/moon.png",
  "w": 160,
  "h": 136,
  "frames": 6,
  "durations": [
   260,
   260,
   260,
   260,
   260,
   260
  ]
 },
 "bee": {
  "src": "assets/sprites/bee.png",
  "w": 76,
  "h": 76,
  "frames": 2,
  "durations": [
   110,
   110
  ]
 },
 "hibiscus": {
  "src": "assets/sprites/hibiscus.png",
  "w": 160,
  "h": 128,
  "frames": 6,
  "durations": [
   240,
   240,
   240,
   240,
   240,
   240
  ]
 },
 "mew": {
  "src": "assets/sprites/mew.png",
  "w": 132,
  "h": 136,
  "frames": 8,
  "durations": [
   150,
   150,
   150,
   150,
   150,
   150,
   150,
   150
  ]
 },
 "mew-sleep": {
  "src": "assets/sprites/mew-sleep.png",
  "w": 136,
  "h": 112,
  "frames": 8,
  "durations": [
   280,
   280,
   280,
   280,
   280,
   280,
   280,
   280
  ]
 },
 "cutiefly": {
  "src": "assets/sprites/cutiefly.png",
  "w": 124,
  "h": 124,
  "frames": 12,
  "durations": [
   90,
   90,
   90,
   90,
   90,
   90,
   90,
   90,
   90,
   90,
   90,
   90
  ]
 },
 "stitch": {
  "src": "assets/sprites/stitch.png",
  "w": 154,
  "h": 146,
  "frames": 8,
  "durations": [
   1600,
   110,
   900,
   120,
   140,
   120,
   1300,
   110
  ]
 },
 "stitch-hula": {
  "src": "assets/sprites/stitch-hula.png",
  "w": 480,
  "h": 270,
  "frames": 16,
  "durations": [
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70
  ]
 },
 "stitch-hi": {
  "src": "assets/sprites/stitch-hi.png",
  "w": 480,
  "h": 270,
  "frames": 20,
  "durations": [
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   60,
   70,
   70,
   70
  ]
 }
};
